spring.application.name=Mercado
spring.datasource.url=jdbc:h2:file:./data/mercado_db
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuraciones de Multipart para subida de imagenes (Iteracion 7)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
# Actuator Config
management.endpoints.web.exposure.include=health,metrics,info
# Permitir CORS para Spring Boot Actuator (Dashboard React)
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=GET,POST

# Credenciales de Superadministrador (Iteracion 38)
app.superadmin.nombre=Santiago
app.superadmin.ci=1000000
app.superadmin.expedido=SC
app.superadmin.password=Mutualista2026!
